# docker-compose.yml은 실제 AWS EB에서 작동시킬거임!
# AWS의 EB는 RDS를 생성하기 때문에, MySQL 컨테이너를 생성할 필요가 없어서 주석처리 함
version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mydatabase
#      SPRING_DATASOURCE_USERNAME: user
#      SPRING_DATASOURCE_PASSWORD: password
#    depends_on:
#      - db

#  db:
#    image: mysql:5.7
#    environment:
#      MYSQL_DATABASE: mydatabase
#      MYSQL_USER: user
#      MYSQL_PASSWORD: password
#      MYSQL_ROOT_PASSWORD: rootpassword
#    ports:
#      - "3306:3306"
#    volumes:
#      - db-data:/var/lib/mysql
#
#volumes:
#  db-data: