name: Deploy Backend and MySQL

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
#      - run: docker build -t doubledrg/spring ./
#      이건 MySQL이 설치되지 않은 CI서버에서 테스트해보는 용도라서
#      spring프로젝트 + MySQL 컨테이너를 모두 생성하는 docker-compose-dev.yml을 사용해야 함
      - run: docker-compose-dev up

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: spring-mysql-docker-app
          environment_name: Spring-mysql-docker-app-env
          existing_bucket_name: elasticbeanstalk-ap-northeast-2-270238917308
          region: ap-northeast-2
          version_label: ${{ github.sha}}
          deployment_package: deploy.zip